=== zhangkangmu/javacommon/standardCode/src/web相关/day00_XML和dom4j/demo3_schema/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.itheima.com/ee23" 
elementFormDefault="qualified">
	<element name="books">
		<complexType>
			<sequence maxOccurs="2" minOccurs="2">
				<element name="book">
					<complexType>
						<sequence>
								<element name="name" type="string"></element>
								<element name="author" type="string"></element>
								<element name="price" type="double"></element>
						</sequence>
						<attribute name="bid" type="int" use="optional"/>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== zhangkangmu/javacommon/standardCode/src/web相关/day00_XML和dom4j/demo3_schema/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 引入W3C规定的实例文档的名称空间. -->
<books 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.itheima.com/ee23"
xsi:schemaLocation="http://www.itheima.com/ee23 book.xsd"
>
	<book bid="1">
		<name>斗破苍穹</name>
		<author>天蚕土豆</author>
		<price>98.8</price>
	</book>

	<book bid="2">
		<name>斗罗大陆</name>
		<author>唐家三少</author>
		<price>98.8</price>
	</book>
</books>
